meals = 
['korean rice bowls',
'pizza',
'mac and cheese',
'steak',
'salmon burgers',
'burgers',
'gumbo',
'breakfast for dinner',
'yogurt chicken with couscous',
'roast',
'meatloaf',
'stir-fry',
'fajitas',
'tacos',
'nachos',
'cobb salad',
'stroganoff',
'salisbury steak',
'fish',
'carnitas',
'swedish meetaballs',
'ramen',
'shirmp skampi',
'spagetti',
'fettacini alfreado',
'soup',
'chili',
'fried chicken',
'tuna',
'chicken salad',
'enchiladas',
'ribs',
'wings',
'blt',
'chicken bowl',
'sushi',
'walking tacos',
'cajun chicken pasta',
'hot dogs',
'momo potatoes',
'wraps',
'lasagna',
'stromboli',
'pulled pork',
'baked potato',
'grilled cheese',
'chicken fried steak',
'corn dogs',
'burritos',
'ham',
'pork chops',
'french dip',
'corned beef and cabbage',
'chicken pillows',
'carbonara',
'crunch wraps',
'baked ziti',
'beef and brocoli',
'chicken parmesan',
'chicken marsala',
'chicken nuggets',
'cheese steak',
'grilled chicken',
'chicken and waffles',
'eggs benedict',
'filet mignon',
'beef wellington',
'sliders',
'poppy seed chicken',
'pretzels',
'stuffed mushrooms',
'chicken parmigiana',
'split pea soup',
'crockpot chicken and stuffing',
'cafe rioesqe',
'ravioli',
'tortelini',
'chicken different',
'chicken cordon blue',
'garlic knots',
'lentil soup',
'irish nachos',
'cheese board',
'pasta salad',
'picadillo',
'erepas',
'ceasar salad',
'sausage and peppers',
'tamales',
'stuffed smoked pork loin',
'fried rice',
'quesadillas',
'beefy mac',
'sloppy joes',
'hamburger salad',
'biria tacos'
]